name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v3
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: '16.x'
      # build
      - run: yarn install --frozen-lockfile
      - run: tsc && vite build
      # deploy
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
